### PR TITLE
indev: Add HAL layer for Input device driver

### PR DESCRIPTION
**Pull request by ajaybhargav**
This patch adds HAL layer for Input devices like keyboard/mouse/push buttons/touch panel etc.

To register input device driver:

```
    /**
     * Driver structure
     */
    indev_drv_t tp_driver {
        .name = "MyTouchPanel",
        .type = INDEV_TYPE_TOUCH,
        .init = mytp_init,
    };

    /* To report New touch input */
    indev_t report;

    report.type = INDEV_TYPE_TOUCH;
    report.data.touch.x = x_coord;
    report.data.touch.y = y_coord;
    report.data.touch.longpress = 0;
    hal_indev_report(&report);

    /* To disable input from specific type e.g. say Keypad */
    hal_indev_disable(INDEV_TYPE_KEYPAD);
```

Signed-off-by: Ajay Bhargav <contact@rickeyworld.info>

### CODE REVIEW

**Comment by ajaybhargav** [comment]
Its a kind of first draft... But HAL will have more flexibility on type of input device. Even push buttons can be used to do specific tasks.

**Comment by kisvegabor** [comment]
Thank you for the patch! I've checked it and the following things came to my mind:

**The big question**
In my opinion an important goal is to make the LittlevGL integration to a hardware as simple as possible. In this version the user has to periodically read and report data and handle long pressing. 
Now (in v4.2) long pressing and periodical reading is handled in the library. In my opinion it requires more simple drivers (only e.g. touch_read() required). It also ensure the opportunity to add other actions (like double click) without modifying the drivers. In addition in this way the the whole process become thread safe because devices are asked sequentially. What do you think?

**Small things**
* HAL_OK might conflict with an other HAL library
* KEY_... in enum?
* Let *init* functions for the user? (to make hal more simple)  
* Pointer means Mouse?
* for consistency public typdefs should start with *hal_indev*

**Ideas**
* Multi touch support for touch pad?
* Scroll wheel support for mouse?

**Comment by kisvegabor** [comment]
One more idea: Keypad and Push buttons  can be two different input device:
**Keypad** keyboard with a lot of buttons reacting with the object in focus
**Push button(s)** A single (or more) button which presses a specific point on the screen (like on [oscilloscopes](https://www.google.hu/search?biw=2133&bih=1067&tbm=isch&sa=1&q=oscilloscope+difital&oq=oscilloscope+difital&gs_l=psy-ab.3..0i19k1j0i8i13i30i19k1l3.28210.29635.0.29760.8.8.0.0.0.0.89.629.8.8.0....0...1.1.64.psy-ab..0.6.486...0i30i19k1j0i8i30i19k1.Aty6-VJtF88#imgrc=8LRAHmb-It71iM:))

**Comment by ajaybhargav** [comment]
> In this version the user has to periodically read and report data and handle long pressing.

Long pressing detection can be removed from HAL I just kept it like that as a though. However driver need not to read periodic data. Most of the systems there is availability of interrupts so user driver need not to have a periodic read. e.g. touch panel have pendown IRQ, Pushbutton and keypad has onchange events etc. The report must be called so handling of data can be done outside interrupt which will be done by existing periodic read of library. So the task of user driver will be to only detect and push the data and library periodically read from queue and process it. This will rather make driver more simpler.

Secondly keeping a generic layer of HAL will help in better key processing. e.g. let say you have 4 keys in your system which you want to use for navigation up/down/left/right. So on key press you can push key code of up/down/left/right respectively which will also be compatible if you have any other keypad in place so only key code has to be supplied by driver action on that key can be defined by application. This will reduce the need of having separate handlers for push buttons or keypads.

As of now keyboard of lvgl is in application layer whereas with HAL we can hook software keypad to simulate and report key press events to library which will act as if a physical keyboard is pressed.

This HAL will also need a translation which will translate keycode to respective function, e.g. if A keycode is returned, lvgl needs to decide whether to get ascii of it or to do action for A. Like we have click action, similarly we can have key actions.

Am I taking a longer route? 😕 

> Let init functions for the user? (to make hal more simple)

either way... at least one of them has to call it. Keeping it as a function pointer make sure that everything happens in a proper flow rather than things are being called off track.

> KEY_... in enum?

aaa ok... 🤔 its a long one...

> Pointer means Mouse?

Yes

> for consistency public typdefs should start with hal_indev

I dont mind but length of structure names will increase... might look ugly at some places.

**Comment by kisvegabor** [comment]
Ok, you've convinced me about reporting vs periodic reading. :) 
But lets think about the keyboard usage: If you only have got a keyboard (no mouse, no touchpad) you can navigate only from one object to an other (like using tab key on a PC). It still okay because - as you said - you can assign actions (somehow) to buttons (like next/prev object) or write ASCII letters. 

However a soft keyboard works differently because in this case yo have touchpad to choose a destination object (e.g. a Text area)  or navigate with normal GUI buttons. So I think soft keypad is different story.  But agree with the rest! :) 

I agree with keeping init function in the HAL too. 

hal_indev..._t: yes it will look uglier... but I myself prefer consistency. :)

 What about multi touch, mouse scroll wheel and push button to press GUI? Do find them useful?

**Comment by ajaybhargav** [comment]
> hal_indev..._t: yes it will look uglier... but I myself prefer consistency. :)

will change that... So from our discussion. I am not able to figure out if I need to change anything there or not? 😆 

> What about multi touch, mouse scroll wheel and push button to press GUI? Do find them useful?

Multitouch wont be available in case of embedded devices I guess. and mouse wheel can only be used for scroll (which can be useful in some cases) but I have least idea about it.

**Comment by kisvegabor** [comment]
> I am not able to figure out if I need to change anything there or not? 

Sorry, I'm just trying not to be rude or "give orders". So, please use *hal_indev..._t* format.  :)

Multi touch and scroll: I have the same thoughts but I was curious maybe you know some good use cases. :) However the push button things are viable and might be commonly use in my opinion. Just need to assign a coordinate to a button.

I mentioned a few things about keyboard usage. Do yo agree with that?

**Comment by kisvegabor** [comment]
Anyway this pull request seems a good direction. So I merge it!

**Comment by kisvegabor** [comment]
I've created `dev-5.0` branch for `misc` too. In lvgl:dev-5.0 I added
- *misc* as submodule
- *hal* with git clone (as it will be added later as normal folder)

A few things to mention:
- There was some compiler  issues in *hal_disp* and *hal_indev* but I fixed and pushed them
- As *hal* folder will have only a few files don't need to use folders for disp and indev
- What about using FIFO in indev for reported data instead of linked list? (FIFO has less overhead)
- Now the project compiles but lvgl still not using functions from hal (commented them)

Well done Ajay! Your contribution helps a lot!

**Comment by ajaybhargav** [comment]
Hi Gabor,
Sorry I was busy this weekend. Hope you also had a good time. I was thinking to fix the naming issues before you merge it. Did you fix them already?

> As hal folder will have only a few files don't need to use folders for disp and indev

Yes I agree completely.

> What about using FIFO in indev for reported data instead of linked list? (FIFO has less overhead)

That would be perfect and intention was to have a fifo so I used LL as fifo.

> Now the project compiles but lvgl still not using functions from hal 

Yes there will be significant changes to be done in lvgl in order to do that i guess. especially in case of indev. display is far simpler as there is no change in function prototypes.

> It seems this architecture will be much better! So well done Ajay! Your contribution helps a lot!

I am glad. After all if I am going to use this library I have to give back something 😄

**Comment by kisvegabor** [comment]
Hi Ajay,
no problem, take your time. I had a busy weekend too :)

Thank you for the planned updates. 
_misc_ already has a FIFO module, maybe it can be used here. 

Meanwhile I applied to hal_disp in lvgl. It was quite easy but some problem appeared related to misc. I posted about it in its issue: https://github.com/littlevgl/lvgl/issues/18

**Pull request merged**
